sudo: required

services: docker

# 環境変数はtravis, herokuで設定できる！
env: 
  global: 
    - DOCKER_USERNAME=sh14124869
    - DOCKER_ACCESS_TOKEN=35184576-4722-4925-acae-f1719bba0c88

before_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
  - docker-compose up --build -d
  - docekr login -u $HEROKU_USERNAME -p $HEROKU_API_KEY registry.heroku.com
script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test

deploy: 
  provider: script
  script: 
    docker build -t regisrty.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile.prod .;
    docker push regisrty.heroku.com/$HEROKU_APP_NAME/web;
    heroku run --app $HEROKU_APP_NAME rails db:migrate;

  on: 
    branch: master