sudo: required

services: docker

env: 
  global: 
    - DOCKER_USERNAME=sh14124869
    - DOCKER_ACCESS_TOKEN=35184576-4722-4925-acae-f1719bba0c88

before_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test